import { createHash } from "node:crypto";
import { parse, stringify } from "smol-toml";

import {
  budgetedConfigurationSchema,
  liveSecretsSchema,
  type BudgetedConfiguration,
  type LiveSecrets,
  type ConfigurationDocument,
} from "../shared/contracts";

export type SstSecretName =
  | "AuthSecret"
  | "AmazonOrderScraperApiToken"
  | "PlaidClientId"
  | "PlaidSecret"
  | "OpenAiApiKey"
  | "GoogleGenerativeAiApiKey";

export function validateSecrets(configuration: BudgetedConfiguration, input: LiveSecrets, options?: { requireAdmin?: boolean }) {
  const secrets = liveSecretsSchema.parse(input);
  const missing: string[] = [];
  if (configuration.amazonOrders.enabled && !secrets.amazonOrderScraperApiToken) missing.push("Amazon Orders API token");
  if (configuration.plaid.enabled && !secrets.plaidClientId) missing.push("Plaid client ID");
  if (configuration.plaid.enabled && !secrets.plaidSecret) missing.push("Plaid secret");
  if (configuration.ai.openAiEnabled && !secrets.openAiApiKey) missing.push("OpenAI API key");
  if (configuration.ai.googleEnabled && !secrets.googleGenerativeAiApiKey) missing.push("Google AI API key");
  if (options?.requireAdmin && !secrets.adminPassword) missing.push("initial administrator password");
  if (missing.length) throw new Error(`Missing required credentials: ${missing.join(", ")}.`);
  return secrets;
}

export function createSstSecrets(configuration: BudgetedConfiguration, input: LiveSecrets, authSecret?: string) {
  const secrets = liveSecretsSchema.parse(input);
  const output = new Map<SstSecretName, string>();
  if (authSecret) output.set("AuthSecret", authSecret);
  if (configuration.amazonOrders.enabled && secrets.amazonOrderScraperApiToken) output.set("AmazonOrderScraperApiToken", secrets.amazonOrderScraperApiToken);
  if (configuration.plaid.enabled && secrets.plaidClientId && secrets.plaidSecret) {
    output.set("PlaidClientId", secrets.plaidClientId);
    output.set("PlaidSecret", secrets.plaidSecret);
  }
  if (configuration.ai.openAiEnabled && secrets.openAiApiKey) output.set("OpenAiApiKey", secrets.openAiApiKey);
  if (configuration.ai.googleEnabled && secrets.googleGenerativeAiApiKey) output.set("GoogleGenerativeAiApiKey", secrets.googleGenerativeAiApiKey);
  return output;
}

export function generateBudgetedToml(input: BudgetedConfiguration) {
  const configuration = budgetedConfigurationSchema.parse(input);
  const stage: Record<string, unknown> = {
    deployment: {
      protect: configuration.advanced.protect,
      removal: configuration.advanced.removal,
    },
    integrations: {
      ...(configuration.amazonOrders.enabled
        ? { amazonOrders: { apiUrl: configuration.amazonOrders.apiUrl } }
        : {}),
      plaid: { environment: configuration.plaid.environment },
    },
    infrastructure: {
      artifacts: {
        ledgerExportRetentionDays: configuration.advanced.ledgerExportRetentionDays,
        ynabImportRetentionDays: configuration.advanced.ynabImportRetentionDays,
        ynabImportAllowedOrigins: configuration.advanced.ynabImportAllowedOrigins,
      },
      assetLifecycle: {
        enabled: configuration.advanced.assetLifecycleEnabled,
        repository: configuration.advanced.assetRepository,
        expireUntaggedAfterDays: configuration.advanced.assetExpireUntaggedAfterDays,
      },
      automation: {
        enabled: configuration.advanced.automationEnabled,
        schedule: configuration.advanced.automationSchedule,
        retries: configuration.advanced.automationRetries,
        timeout: configuration.advanced.automationTimeout,
      },
      ynabImportWorker: {
        memory: configuration.advanced.ynabWorkerMemory,
        timeout: configuration.advanced.ynabWorkerTimeout,
      },
      web: { timeout: configuration.advanced.webTimeout },
    },
  };

  if (configuration.domain.mode !== "none") {
    stage.webDomain = configuration.domain.mode === "external"
      ? { name: configuration.domain.name, dns: "external", cert: configuration.domain.certificateArn }
      : { name: configuration.domain.name, dns: "aws", ...(configuration.domain.zoneId ? { route53ZoneId: configuration.domain.zoneId } : {}) };
  }
  if (configuration.venmoEmail.enabled) {
    stage.venmoEmail = {
      recipient: configuration.venmoEmail.recipient,
      dns: configuration.venmoEmail.dns,
      ...(configuration.venmoEmail.allowedForwarders.length ? { allowedForwarders: configuration.venmoEmail.allowedForwarders } : {}),
      ...(configuration.venmoEmail.route53ZoneId ? { route53ZoneId: configuration.venmoEmail.route53ZoneId } : {}),
    };
  }

  return `# Generated by Budgeted Launcher. Credentials are stored as SST secrets.\n\n${stringify({
    app: {
      name: configuration.appName,
      productionStage: configuration.productionStage,
    },
    stages: { [configuration.productionStage]: stage },
  })}\n`;
}

type TomlObject = Record<string, unknown>;

export function parseBudgetedToml(toml: string, preserved?: BudgetedConfiguration): BudgetedConfiguration {
  const document = parse(toml) as TomlObject;
  const app = objectAt(document, "app");
  const appName = stringAt(app, "name");
  const productionStage = stringAt(app, "productionStage");
  const stages = objectAt(document, "stages");
  const stage = objectAt(stages, productionStage);
  const deployment = optionalObjectAt(stage, "deployment");
  const integrations = optionalObjectAt(stage, "integrations");
  const amazonOrders = optionalObjectAt(integrations, "amazonOrders");
  const plaid = optionalObjectAt(integrations, "plaid");
  const infrastructure = optionalObjectAt(stage, "infrastructure");
  const artifacts = optionalObjectAt(infrastructure, "artifacts");
  const assetLifecycle = optionalObjectAt(infrastructure, "assetLifecycle");
  const automation = optionalObjectAt(infrastructure, "automation");
  const ynabWorker = optionalObjectAt(infrastructure, "ynabImportWorker");
  const web = optionalObjectAt(infrastructure, "web");
  const webDomain = optionalObjectAt(stage, "webDomain");
  const venmo = optionalObjectAt(stage, "venmoEmail");
  assertLauncherTomlShape(document, app, stages, productionStage, stage);

  const domain = Object.keys(webDomain).length === 0
    ? { mode: "none" as const }
    : stringAt(webDomain, "dns") === "external"
      ? { mode: "external" as const, name: stringAt(webDomain, "name"), certificateArn: stringAt(webDomain, "cert") }
      : { mode: "route53" as const, name: stringAt(webDomain, "name"), ...(optionalStringAt(webDomain, "route53ZoneId") ? { zoneId: optionalStringAt(webDomain, "route53ZoneId") } : {}) };
  const venmoEmail = Object.keys(venmo).length === 0
    ? { enabled: false as const }
    : {
        enabled: true as const,
        recipient: stringAt(venmo, "recipient"),
        allowedForwarders: stringArrayAt(venmo, "allowedForwarders", []),
        dns: enumAt(venmo, "dns", ["external", "aws"] as const, "external"),
        ...(optionalStringAt(venmo, "route53ZoneId") ? { route53ZoneId: optionalStringAt(venmo, "route53ZoneId") } : {}),
      };

  return budgetedConfigurationSchema.parse({
    appName,
    productionStage,
    domain,
    amazonOrders: { enabled: Object.keys(amazonOrders).length > 0, apiUrl: optionalStringAt(amazonOrders, "apiUrl") ?? "" },
    plaid: { enabled: preserved?.plaid.enabled ?? false, environment: enumAt(plaid, "environment", ["sandbox", "development", "production"] as const, "sandbox") },
    ai: {
      openAiEnabled: preserved?.ai.openAiEnabled ?? false,
      googleEnabled: preserved?.ai.googleEnabled ?? false,
    },
    venmoEmail,
    advanced: {
      protect: optionalBooleanAt(deployment, "protect") ?? true,
      removal: enumAt(deployment, "removal", ["remove", "retain", "retain-all"] as const, "retain"),
      ledgerExportRetentionDays: optionalNumberAt(artifacts, "ledgerExportRetentionDays") ?? 1,
      ynabImportRetentionDays: optionalNumberAt(artifacts, "ynabImportRetentionDays") ?? 2,
      ynabImportAllowedOrigins: stringArrayAt(artifacts, "ynabImportAllowedOrigins", ["*"]),
      assetLifecycleEnabled: optionalBooleanAt(assetLifecycle, "enabled") ?? true,
      assetRepository: optionalStringAt(assetLifecycle, "repository") ?? "sst-asset",
      assetExpireUntaggedAfterDays: optionalNumberAt(assetLifecycle, "expireUntaggedAfterDays") ?? 3,
      automationEnabled: optionalBooleanAt(automation, "enabled") ?? true,
      automationSchedule: optionalStringAt(automation, "schedule") ?? "cron(0/2 * * * ? *)",
      automationRetries: optionalNumberAt(automation, "retries") ?? 0,
      automationTimeout: optionalStringAt(automation, "timeout") ?? "15 minutes",
      ynabWorkerMemory: optionalStringAt(ynabWorker, "memory") ?? "2 GB",
      ynabWorkerTimeout: optionalStringAt(ynabWorker, "timeout") ?? "15 minutes",
      webTimeout: optionalStringAt(web, "timeout") ?? "60 seconds",
    },
  });
}

export function createConfigurationDocument(configuration: BudgetedConfiguration, revision = 0): ConfigurationDocument {
  const structured = budgetedConfigurationSchema.parse(configuration);
  return { structured, toml: generateBudgetedToml(structured), source: "structured", revision, updatedAt: new Date().toISOString() };
}

export function createConfigurationFingerprint(input: {
  awsAccountId: string;
  awsRegion: string;
  releaseCommit: string;
  configuration: ConfigurationDocument;
}) {
  const value = [input.awsAccountId, input.awsRegion, input.configuration.structured.appName, input.configuration.structured.productionStage, input.releaseCommit, input.configuration.toml].join("\n");
  return createHash("sha256").update(value).digest("hex");
}

function objectAt(value: TomlObject, key: string): TomlObject {
  const item = value[key];
  if (!item || typeof item !== "object" || Array.isArray(item)) throw new Error(`TOML field ${key} must be a table.`);
  return item as TomlObject;
}

function optionalObjectAt(value: TomlObject, key: string): TomlObject {
  const item = value[key];
  if (item === undefined) return {};
  if (!item || typeof item !== "object" || Array.isArray(item)) throw new Error(`TOML field ${key} must be a table.`);
  return item as TomlObject;
}

function stringAt(value: TomlObject, key: string) {
  const item = value[key];
  if (typeof item !== "string" || !item) throw new Error(`TOML field ${key} must be a non-empty string.`);
  return item;
}

function optionalStringAt(value: TomlObject, key: string) {
  const item = value[key];
  if (item === undefined) return undefined;
  if (typeof item !== "string") throw new Error(`TOML field ${key} must be a string.`);
  return item;
}

function optionalBooleanAt(value: TomlObject, key: string) {
  const item = value[key];
  if (item === undefined) return undefined;
  if (typeof item !== "boolean") throw new Error(`TOML field ${key} must be a boolean.`);
  return item;
}

function optionalNumberAt(value: TomlObject, key: string) {
  const item = value[key];
  if (item === undefined) return undefined;
  if (typeof item !== "number") throw new Error(`TOML field ${key} must be a number.`);
  return item;
}

function stringArrayAt(value: TomlObject, key: string, fallback: string[]) {
  const item = value[key];
  if (item === undefined) return fallback;
  if (!Array.isArray(item) || item.some((entry) => typeof entry !== "string")) throw new Error(`TOML field ${key} must be an array of strings.`);
  return item as string[];
}

function enumAt<const T extends readonly string[]>(value: TomlObject, key: string, options: T, fallback: T[number]): T[number] {
  const item = value[key];
  if (item === undefined) return fallback;
  if (typeof item !== "string" || !options.includes(item)) throw new Error(`TOML field ${key} has an unsupported value.`);
  return item as T[number];
}

function assertLauncherTomlShape(document: TomlObject, app: TomlObject, stages: TomlObject, productionStage: string, stage: TomlObject) {
  assertKeys(document, ["app", "stages"], "document");
  assertKeys(app, ["name", "productionStage"], "app");
  assertKeys(stages, [productionStage], "stages");
  assertKeys(stage, ["deployment", "infrastructure", "integrations", "venmoEmail", "webDomain"], `stages.${productionStage}`);
  assertKeys(optionalObjectAt(stage, "deployment"), ["protect", "removal"], "deployment");
  assertKeys(optionalObjectAt(stage, "integrations"), ["amazonOrders", "plaid"], "integrations");
  assertKeys(optionalObjectAt(optionalObjectAt(stage, "integrations"), "amazonOrders"), ["apiUrl"], "integrations.amazonOrders");
  assertKeys(optionalObjectAt(optionalObjectAt(stage, "integrations"), "plaid"), ["environment"], "integrations.plaid");
  assertKeys(optionalObjectAt(stage, "webDomain"), ["name", "dns", "cert", "route53ZoneId"], "webDomain");
  assertKeys(optionalObjectAt(stage, "venmoEmail"), ["recipient", "dns", "allowedForwarders", "route53ZoneId"], "venmoEmail");
  const infrastructure = optionalObjectAt(stage, "infrastructure");
  assertKeys(infrastructure, ["artifacts", "assetLifecycle", "automation", "ynabImportWorker", "web"], "infrastructure");
  assertKeys(optionalObjectAt(infrastructure, "artifacts"), ["ledgerExportRetentionDays", "ynabImportRetentionDays", "ynabImportAllowedOrigins"], "infrastructure.artifacts");
  assertKeys(optionalObjectAt(infrastructure, "assetLifecycle"), ["enabled", "repository", "expireUntaggedAfterDays"], "infrastructure.assetLifecycle");
  assertKeys(optionalObjectAt(infrastructure, "automation"), ["enabled", "schedule", "retries", "timeout"], "infrastructure.automation");
  assertKeys(optionalObjectAt(infrastructure, "ynabImportWorker"), ["memory", "timeout"], "infrastructure.ynabImportWorker");
  assertKeys(optionalObjectAt(infrastructure, "web"), ["timeout"], "infrastructure.web");
}

function assertKeys(value: TomlObject, allowed: string[], path: string) {
  const unknown = Object.keys(value).filter((key) => !allowed.includes(key));
  if (unknown.length) throw new Error(`Unsupported TOML field ${path}.${unknown[0]}.`);
}
